{
 "title": "Cluster Custom Metrics",
 "tags": [
  "openshift",
  "egress",
  "monitoring"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Summary of network IPs",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ips_vlan_total - nodesips_uso - egressips_uso",
     "legendFormat": "VLAN Total IPs"
    },
    { "expr": "nodesips_uso", "legendFormat": "Nodes IPs" },
    { "expr": "egressips_uso", "legendFormat": "EgressIP" }
   ]
  },
  {
   "title": "Namespaces without NetworkPolicy",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "namespaces_sin_networkpolicy_total"
    }
   ]
  },
  {
   "title": "Namespaces without ResourceQuota",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "namespaces_sin_resourcequota_total"
    }
   ]
  },
  {
   "title": "Namespaces without NetworkPolicy",
   "type": "table",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 12 },
   "targets": [
    { "expr": "namespace_sin_networkpolicy", "legendFormat": "Namespace" }
   ]
  },
  {
   "title": "Namespaces without ResourceQuota",
   "type": "table",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 12 },
   "targets": [
    { "expr": "namespace_sin_quota" }
   ]
  }
 ]
}