kind: ConfigMap
apiVersion: v1
metadata:
  name: cluster-custom-config
  namespace: cluster-monitoring
immutable: false
data:
  config.json: |-
    {
      "subnet": "10.10.10.0/24",
      "exclude_namespaces": ["openshift-*", "kube-*", "default"]
    }
