apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: networkpolicy-rules
  namespace: cluster-monitoring
spec:
  groups:
  - name: networkpolicy
    rules:
    - alert: NamespaceWithoutNetworkPolicy
      expr: namespace_without_networkpolicy > 0
      for: 5m
      labels:
        severity: warning
        namespace: '{{ $labels.namespace }}'
      annotations:
        summary: "Namespace {{ $labels.namespace }} lacks NetworkPolicy"
        description: "Namespace {{ $labels.namespace }} does not define any NetworkPolicy."
