apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: no-resource-rules
  namespace: cluster-monitoring
spec:
  groups:
  - name: no-resource
    rules:
    - alert: WorkloadWithoutResources
      expr: workloads_no_resources_total > 0
      for: 15m
      labels:
        severity: warning
      annotations:
        summary: "Workload without resource requests or limits"
        description: "Some workloads lack resource requests or limits."
