apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: resourcequota-rules
  namespace: cluster-monitoring
spec:
  groups:
  - name: resourcequota
    rules:
    - alert: NamespaceWithoutResourceQuota
      expr: namespaces_without_resourcequota_total > 0
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "Namespaces missing ResourceQuota"
        description: "Some namespaces do not have any ResourceQuota defined."
